softdepend: [NBTAPI, ProtocolLib]
name: ClusterFactions
version: Alpha v1.0
author: ClusterFactions
api-version: 1.16
main: com.clusterfactions.clustercore.ClusterCore
description: ClusterFactions Factiosn Core